accumulating_gradients: true
base_lr: 0.1
batch_size: 2
bn_flag: true
cl_mode: null
cl_version: V0
clip: false
clip_grad_norm: 0.5
complete: true
config: config/st_gcn/nturgbd/train.yaml
data_dir: null
data_mirroring: false
device:
- 0
- 1
- 2
- 3
display_by_category: false
display_recall_precision: false
eval_interval: 10
exp_name: prova20
feeder: st_gcn.feeder.Feeder
feeder_augmented: st_gcn.feeder.FeederAugmented
gcn0_flag: false
ignore_weights: []
local_rank: 0
log_dir: ./checkpoints/prova20
log_interval: 100
model: st_gcn.net.ST_GCN
model_args:
  Nh: 8
  adjacency: false
  agcn: false
  all_layers: false
  attention: true
  attention_3: false
  bn_flag: true
  channel: 6
  concat_original: true
  data_normalization: true
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  dk: 0.25
  double_channel: true
  drop_connect: true
  dv: 0.25
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: spatial
  kernel_temporal: 9
  mask_learning: true
  more_channels: false
  n: 4
  num_class: 60
  num_person: 2
  num_point: 25
  only_attention: true
  only_temporal_attention: true
  relative: false
  skip_conn: true
  tcn_attention: false
  use_data_bn: true
  visualization: false
  weight_matrix: 2
  window_size: 300
nesterov: true
num_epoch: 2
num_worker: 10
num_workers: 10
optimize_every: 2
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: true
scheduler: 1
scheduling_lr: true
seed: 13696642
show_topk:
- 1
- 5
start_cl_epoch: -1
start_epoch: 0
step:
- 60
- 90
test_batch_size: 8
test_feeder_args:
  data_path: ../Output_skeletons_without_missing_skeletons/xsub/val_data_joint_bones.npy
  label_path: ../Output_skeletons_without_missing_skeletons/xsub/val_label_filtered.pkl
test_feeder_args_new: {}
train_feeder_args:
  data_path: ../Output_skeletons_without_missing_skeletons/xsub/train_data_joint_bones.npy
  label_path: ../Output_skeletons_without_missing_skeletons/xsub/train_label_filtered.pkl
  mirroring: false
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
train_feeder_args_new: {}
training: true
val_split: 0.2
validation_split: false
w_cl_loss: 0.1
w_multi_cl_loss:
- 0.1
- 0.2
- 0.5
- 1
weight_decay: 0.0001
weights: null
work_dir: ./prova20
writer_enabled: true
